Repository newsIntelligent/Backend, pull requests merged in 2025-07, with the labels that each got.

#3 feat: #2 도메인 엔티티 구현
  .gitignore
  src/main/java/UMC/news/newsIntelligent/domain/dailyReport/DailyReport.java
  src/main/java/UMC/news/newsIntelligent/domain/feedback/Feedback.java
  src/main/java/UMC/news/newsIntelligent/domain/member/Member.java
  src/main/java/UMC/news/newsIntelligent/domain/member/MemberTopic.java
  src/main/java/UMC/news/newsIntelligent/domain/news/News.java
  src/main/java/UMC/news/newsIntelligent/domain/newsCategory/NewsCategory.java
  src/main/java/UMC/news/newsIntelligent/domain/notification/Notification.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/Topic.java
  src/main/resources/env.properties
  src/main/resources/schema.sql
Labels: :sparkles: feature

#5 refactor: #4 Notification 엔티티 수정
  src/main/java/UMC/news/newsIntelligent/domain/notification/Notification.java
  src/main/java/UMC/news/newsIntelligent/domain/notification/NotificationType.java
Labels: :recycle: refactor

#11 chore: CORS 설정
  .gitignore
  docker-compose.yml
  src/main/java/UMC/news/newsIntelligent/global/config/security/SecurityConfig.java
Labels: :rocket: deploy, :label: chore

#14 chore: 멀티스테이지 빌드 적용 및 CI/CD 최적화
  .dockerignore
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
Labels: :rocket: deploy

#10 Feat/#9 : 피드백 기능 구현
  src/main/java/UMC/news/newsIntelligent/domain/feedback/code/FeedbackErrorCode.java
  src/main/java/UMC/news/newsIntelligent/domain/feedback/code/FeedbackSuccessCode.java
  src/main/java/UMC/news/newsIntelligent/domain/feedback/controller/FeedbackController.java
  src/main/java/UMC/news/newsIntelligent/domain/feedback/dto/FeedbackRequestDTO.java
  src/main/java/UMC/news/newsIntelligent/domain/feedback/entity/Feedback.java
  src/main/java/UMC/news/newsIntelligent/domain/feedback/repository/FeedbackRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/feedback/service/command/FeedbackCommandService.java
  src/main/java/UMC/news/newsIntelligent/domain/feedback/service/command/FeedbackCommandServiceImpl.java
Labels: :sparkles: feature

#16 feat: #6 알림 목록 조회 구현
  src/main/java/UMC/news/newsIntelligent/domain/notification/controller/NotificationController.java
  src/main/java/UMC/news/newsIntelligent/domain/notification/dto/NotificationRequest.java
  src/main/java/UMC/news/newsIntelligent/domain/notification/dto/NotificationResponse.java
  src/main/java/UMC/news/newsIntelligent/domain/notification/repository/NotificationRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/notification/service/NotificationService.java
  src/main/java/UMC/news/newsIntelligent/domain/notification/service/NotificationServiceImpl.java
  src/main/java/UMC/news/newsIntelligent/global/apiPayload/code/error/GeneralErrorCode.java
Labels: :sparkles: feature

#19 Feat/#15 : 토픽 조회(검색) 기능 구현
  src/main/java/UMC/news/newsIntelligent/domain/member/controller/MemberTopicController.java
  src/main/java/UMC/news/newsIntelligent/domain/member/converter/MemberTopicConverter.java
  src/main/java/UMC/news/newsIntelligent/domain/member/dto/MemberTopicResponseDTO.java
  src/main/java/UMC/news/newsIntelligent/domain/member/entity/Member.java
  src/main/java/UMC/news/newsIntelligent/domain/member/entity/MemberTopic.java
  src/main/java/UMC/news/newsIntelligent/domain/member/repository/MemberTopicRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/member/service/MemberTopicQueryService.java
  src/main/java/UMC/news/newsIntelligent/domain/member/service/MemberTopicQueryServiceImpl.java
  src/main/java/UMC/news/newsIntelligent/domain/news/News.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/controller/TopicController.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/converter/TopicConverter.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/dto/TopicResponseDTO.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/entity/Topic.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/repository/TopicRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/service/query/TopicQueryService.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/service/query/TopicQueryServiceImpl.java
Labels: :sparkles: feature
