Repository newsIntelligent/Backend, pull requests merged in 2025-08, with the labels that each got.

#38 Fix: validation 추가
  build.gradle
  src/main/java/UMC/news/newsIntelligent/domain/topic/controller/TopicController.java
Labels: :bug: bug

#40 Fix: 빌드 캐시 문제 및 워크플로 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: :bug: bug, :rocket: deploy

#42 Fix: cd compose 변경
  .github/workflows/cd.yml
Labels: :bug: bug, :rocket: deploy

#43 Refactor: swagger 코드 통일
  src/main/java/UMC/news/newsIntelligent/domain/news/controller/NewsController.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/controller/TopicController.java
Labels: :recycle: refactor

#48 Feat: #45 마이페이지 알림 설정 관련 api 구현
  src/main/java/UMC/news/newsIntelligent/domain/dailyReport/DailyReport.java
  src/main/java/UMC/news/newsIntelligent/domain/dailyReport/repository/DailyReportRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/member/controller/MemberSettingController.java
  src/main/java/UMC/news/newsIntelligent/domain/member/dto/MemberSettingRequest.java
  src/main/java/UMC/news/newsIntelligent/domain/member/dto/MemberSettingResponse.java
  src/main/java/UMC/news/newsIntelligent/domain/member/entity/Member.java
  src/main/java/UMC/news/newsIntelligent/domain/member/service/MemberSettingService.java
  src/main/java/UMC/news/newsIntelligent/domain/member/service/MemberSettingServiceImpl.java
  src/main/java/UMC/news/newsIntelligent/global/apiPayload/code/error/GeneralErrorCode.java
Labels: :sparkles: feature

#54 Chore: 운영 서버 cors 설정 추가
  src/main/java/UMC/news/newsIntelligent/global/config/security/SecurityConfig.java
Labels: :label: chore

#55 Fix: PrincipalUserDetails 오류 수정
  src/main/java/UMC/news/newsIntelligent/global/config/security/PrincipalUserDetails.java
  src/main/java/UMC/news/newsIntelligent/global/config/security/SecurityConfig.java
  src/main/java/UMC/news/newsIntelligent/global/config/security/jwt/JwtTokenProvider.java
Labels: :bug: bug

#57 Fix: SecurityContext 오류 수정
  src/main/java/UMC/news/newsIntelligent/global/config/security/SecurityConfig.java
  src/main/java/UMC/news/newsIntelligent/global/config/security/jwt/JwtAuthenticationFilter.java
Labels: :bug: bug

#59 Refactor: 이메일 템플릿 적용
  src/main/java/UMC/news/newsIntelligent/domain/mail/EmailHtmlTemplate.java
  src/main/java/UMC/news/newsIntelligent/domain/mail/service/MailService.java
Labels: :recycle: refactor

#63 Chore: blue-green 적용
  .github/workflows/cd-blue-green.yml
  .github/workflows/cd.yml.disabled
  build.gradle
  docker-compose-prod.yml
  src/main/java/UMC/news/newsIntelligent/global/config/security/SecurityConfig.java
Labels: :rocket: deploy, :label: chore

#64 Fix: blue/green cd script 오류 수정
  .github/workflows/cd-blue-green.yml
  docker-compose-prod.yml
Labels: :bug: bug

#65 Fix: Dockerfile 런타임 이미지 수정
  Dockerfile
  src/main/java/UMC/news/newsIntelligent/global/config/security/SecurityConfig.java
Labels: :bug: bug

#67 Fix: 헬스체크 리밋 적용
  .github/workflows/cd-blue-green.yml
  docker-compose-prod.yml
Labels: :bug: bug

#75 feat: 알림 기능 기초 작업
  src/main/java/UMC/news/newsIntelligent/domain/notification/controller/NotificationController.java
  src/main/java/UMC/news/newsIntelligent/global/config/security/SecurityConfig.java
Labels: :sparkles: feature

#72 Feat: 홈 메인화면(토픽 목록 조회) 구현
  src/main/java/UMC/news/newsIntelligent/domain/topic/controller/TopicController.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/entity/Topic.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/repository/TopicRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/service/query/TopicQueryService.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/service/query/TopicQueryServiceImpl.java
Labels: :sparkles: feature

#80 Fix: TopicQualifiedItemResDTO 누락 필드 추가
  src/main/java/UMC/news/newsIntelligent/domain/news/dto/NewsResponseDTO.java
Labels: :wrench: fix

#81 Fix: 생성자 인자 추가
  src/main/java/UMC/news/newsIntelligent/domain/news/service/NewsQueryServiceImpl.java
Labels: :wrench: fix

#83 refactor: 최신 수정 보도 조건 완화
  src/main/java/UMC/news/newsIntelligent/domain/news/controller/NewsController.java
  src/main/java/UMC/news/newsIntelligent/domain/news/dto/NewsResponseDTO.java
  src/main/java/UMC/news/newsIntelligent/domain/news/repository/NewsRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/news/service/NewsQueryServiceImpl.java
  src/main/java/UMC/news/newsIntelligent/global/apiPayload/code/success/SuccessCode.java
Labels: :recycle: refactor

#87 Refactor: KST로 변경
  src/main/java/UMC/news/newsIntelligent/domain/member/dto/TokenResponseDto.java
  src/main/java/UMC/news/newsIntelligent/domain/member/service/AuthService.java
Labels: :recycle: refactor

#91 Fix: cors 설정 추가
  src/main/java/UMC/news/newsIntelligent/global/config/security/SecurityConfig.java
Labels: :wrench: fix

#94 Refactor: 데일리 리포트 LazyInitializationException 해결
  src/main/java/UMC/news/newsIntelligent/domain/dailyReport/repository/DailyReportRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/dailyReport/scheduler/DailyReportScheduler.java
  src/main/java/UMC/news/newsIntelligent/domain/member/controller/MemberSettingController.java
Labels: :recycle: refactor

#102 Fix: otp code 오류 수정
  src/main/java/UMC/news/newsIntelligent/global/utils/AuthUtils.java
Labels: :bug: bug

#104 Refactor: 홈 화면과 구독 화면 imageSource에 newsLink 추가
  src/main/java/UMC/news/newsIntelligent/domain/member/service/MemberTopicQueryServiceImpl.java
  src/main/java/UMC/news/newsIntelligent/domain/news/repository/NewsRepository.java
  src/main/java/UMC/news/newsIntelligent/domain/news/repository/projection/OldestPerTopicProjection.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/dto/TopicResponseDTO.java
  src/main/java/UMC/news/newsIntelligent/domain/topic/service/query/TopicQueryServiceImpl.java
Labels: :recycle: refactor, :wrench: fix
